[llvm]
targets = "X86"

link-shared = true

[build]
docs = false

extended = true

[install]
prefix = "/opt/rustc-1.42.0"
docdir = "share/doc/rustc-1.42.0"

[rust]
channel = "stable"
rpath = false

codegen-tests = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"

